
- name: Launching AWS ec-2 instances
  hosts: localhost
  connection: local
  tasks:
  - name: launch AWS instance using Ansible
    ec2:
      key_name: Frankfurt-keys-AWS
      instance_type: t2.micro
      image: ami-05f7491af5eef733a
      region: eu-central-1
      wait: yes
      group: Main-ec2
      count: 2
      vpc_subnet_id: subnet-fe63ebb2
      assign_public_ip: yes
      aws_access_key: ***************
      aws_secret_key: ********************
